const crypto = require("crypto");

// Configuration
const ALGORITHM = "aes-256-cbc";
const RAW_KEY = process.env.ENCRYPTION_KEY || "default_fallback_secret"; // Ensure this is set in .env

// Ensure the key is exactly 32 bytes for AES-256
// We use a hash to turn whatever password string you have into a 32-byte buffer
const KEY = crypto.createHash("sha256").update(String(RAW_KEY)).digest();

class Hasher {
  /**
   * Encrypts text.
   * Format returned: "iv_in_hex:encrypted_content_in_hex"
   * This format is URL safe and will not contain '+' symbols.
   */
  static encrypt(text) {
    if (!text) return text;

    // 1. Generate a random Initialization Vector (IV)
    const iv = crypto.randomBytes(16);

    // 2. Create the cipher
    const cipher = crypto.createCipheriv(ALGORITHM, KEY, iv);

    // 3. Encrypt the text and output as Hex (safest for URLs/HTTP)
    let encrypted = cipher.update(text, "utf8", "hex");
    encrypted += cipher.final("hex");

    // 4. Return IV + Encrypted Data joined by a separator (:)
    // We export the IV as hex as well to ensure it's transmission safe
    return `${iv.toString("hex")}:${encrypted}`;
  }

  /**
   * Decrypts the hash generated by the encrypt method.
   */
  static decrypt(hash) {
    if (!hash) return hash;

    try {
      // 1. Split the IV and the Encrypted text
      const parts = hash.split(":");
      
      // Basic validation to ensure format is correct
      if (parts.length !== 2) {
        throw new Error("Invalid hash format");
      }

      const iv = Buffer.from(parts.shift(), "hex");
      const encryptedText = parts.join(":");

      // 2. Create the decipher
      const decipher = crypto.createDecipheriv(ALGORITHM, KEY, iv);

      // 3. Decrypt
      let decrypted = decipher.update(encryptedText, "hex", "utf8");
      decrypted += decipher.final("utf8");

      return decrypted;
    } catch (error) {
      console.error("Decryption failed:", error.message);
      return null; // Or throw, depending on your error handling preference
    }
  }
}

module.exports = { Hasher };